Import('env')

objects = map(env.Object, [
    'asset.cc',
    'asset_loader.cc',
    'asset_manager.cc',
    'component.cc',
    'debug_manager.cc',
    'engine.cc',
    'entity.cc',
    'font.cc',
    'main.cc',
    'mesh.cc',
    'render_target.cc',
    'texture.cc',
    'window.cc',
    'world.cc',
])

objects += SConscript(dirs = [
    'loaders',
])

Return('objects')
