sources = map(File, [
    'asset.cc',
    'asset_loader.cc',
    'asset_manager.cc',
    'debug_manager.cc',
    'engine.cc',
    'font.cc',
    'main.cc',
    'material.cc',
    'mesh.cc',
    'render_target.cc',
    'texture.cc',
    'window.cc',
])

sources += SConscript(dirs = [
    'loaders',
])

Return('sources')
