import os

Import('env')

env['LIBS'] += ['GL', 'GLEW']

objects = map(env.Object, [
    'buffer.cc',
    'commands.cc',
    'fbo.cc',
    'gl.cc',
    'pipeline.cc',
    'program.cc',
    'resource.cc',
    'state.cc',
    'texture.cc',
    'vertex_data.cc',
])

Return('objects')
