import os

Import('env')

if os.uname()[0] == 'Darwin':
    env['FRAMEWORKS'] = ['OpenGL']
else:
    env['LIBS'] += ['GL']

env['LIBS'] += ['GLEW']

objects = map(env.Object, [
    'buffer.cc',
    'commands.cc',
    'fbo.cc',
    'gl.cc',
    'pipeline.cc',
    'program.cc',
    'resource.cc',
    'state.cc',
    'texture.cc',
    'vertex_data.cc',
])

Return('objects')
