import os

Import('env')

if env['PLATFORM'] == 'win32':
    env['LIBS'] += ['vulkan-1']
    env['CPPPATH'] += ["${ENV['VULKAN_SDK']}\Include"]
    env['LIBPATH'] += ["${ENV['VULKAN_SDK']}\Bin"]
else:
    env['LIBS'] += ['vulkan']
    env.ParseConfig('pkg-config --cflags --libs x11-xcb')

objects = map(env.Object, [
    'buffer.cc',
    'commands.cc',
    'command_buffer.cc',
    'device.cc',
    'loader.cc',
    'manager.cc',
    'memory_manager.cc',
    'pipeline.cc',
    'program.cc',
    'queue.cc',
    'render_pass.cc',
    'resource.cc',
    'surface.cc',
    'swapchain.cc',
    'texture.cc',
    'utility.cc',
])

Return('objects')
