import os

Import('env')

env['LIBS'] += ['vulkan']

if os.uname()[0] == 'Linux':
    env.ParseConfig('pkg-config --cflags --libs x11-xcb')

objects = map(env.Object, [
    'buffer.cc',
    'command_buffer.cc',
    'device.cc',
    'loader.cc',
    'memory_manager.cc',
    'queue.cc',
    'resource.cc',
    'stubs.cc',
    'surface.cc',
    'swapchain.cc',
    'vulkan.cc',
])

Return('objects')
