import os

Import('env')

env['LIBS'] += ['vulkan']

if os.uname()[0] == 'Linux':
    env.ParseConfig('pkg-config --cflags --libs x11-xcb')

objects = map(env.Object, [
    'buffer.cc',
    'commands.cc',
    'command_buffer.cc',
    'device.cc',
    'loader.cc',
    'manager.cc',
    'memory_manager.cc',
    'pipeline.cc',
    'program.cc',
    'queue.cc',
    'render_pass.cc',
    'resource.cc',
    'surface.cc',
    'swapchain.cc',
    'texture.cc',
    'utility.cc',
])

Return('objects')
