import os

Import('env')

objects = map(env.Object, [
    'data_stream.cc',
    'engine_global.cc',
    'error.cc',
    'filesystem.cc',
    'hash.cc',
    'log.cc',
    'path.cc',
    'pixel_format.cc',
    'refcounted.cc',
    'string.cc',
])

objects += SConscript(dirs = [
    'math',
])

objects += SConscript(dirs = [os.name])

Return('objects')
