import os

sources = map(File, [
    'data_stream.cc',
    'engine_global.cc',
    'error.cc',
    'filesystem.cc',
    'hash.cc',
    'log.cc',
    'path.cc',
    'pixel_format.cc',
    'refcounted.cc',
    'string.cc',
])

sources += SConscript(dirs = [
    'math',
])

sources += SConscript(dirs = [os.name])

Return('sources')
