Import('env')

objects = map(env.Object, [
    'data_stream.cc',
    'error.cc',
    'filesystem.cc',
    'hash.cc',
    'log.cc',
    'path.cc',
    'pixel_format.cc',
    'refcounted.cc',
    'string.cc',
])

objects += SConscript(dirs = [
    'math',
])

if env['PLATFORM'] in ['linux']:
    objects += SConscript(dirs = ['posix'])
else:
    objects += SConscript(dirs = [env['PLATFORM']])

Return('objects')
