import util

Import('env')

env['CPPPATH'] += [Dir('include')]

objects = []

# 3rd party libraries' SConscripts must be included first so that include
# paths are set correctly.
objects += SConscript(dirs = ['3rdparty'])

# Build utilities.
SConscript(dirs = ['utilities'])

# Build the engine.
objects += util.flatten(SConscript(dirs = [
    'include',
    'src',
]))

Return('objects')
