Import('env')

objects = map(env.ObjgenHeader, [
    #'include/effects/fxaa_effect.h',
    #'include/effects/test_effect.h',
    #'include/post_effect.h',
])

objects += map(env.Object, [
    #'src/draw_list.cc',
    #'src/post_effect.cc',
    #'src/scene.cc',
    #'src/scene_entity.cc',
    #'src/scene_light.cc',
    #'src/scene_renderer.cc',
    #'src/scene_view.cc',
    #'src/effects/fxaa_effect.cc',
    #'src/effects/test_effect.cc',
])

Return('objects')
