Import('env')

objects = SConscript(dirs = [
    'gl',
])

objects += map(env.Object, [
    'buffer.cc',
    'gpu_manager.cc',
    'index_data.cc',
    'pipeline.cc',
    'texture.cc',
    'vertex_data.cc',
    'vertex_format.cc',
])

Return('objects')
