import util

Import('env')

if not Glob(env['GPU_API']):
    util.StopError("GPU API '%s' is not recognised." % (env['GPU_API']))
objects = SConscript(dirs = [env['GPU_API']])

objects += map(env.Object, [
    'buffer.cc',
    'gpu_manager.cc',
    'index_data.cc',
    'pipeline.cc',
    'state.cc',
    'texture.cc',
    'vertex_data.cc',
])

Return('objects')
