sources = SConscript(dirs = [
    'gl',
])

sources += map(File, [
    'buffer.cc',
    'gpu_manager.cc',
    'index_data.cc',
    'pipeline.cc',
    'texture.cc',
    'vertex_data.cc',
    'vertex_format.cc',
])

Return('sources')
