Import('env')

objects = map(env.ObjgenHeader, [
    'player_controller.h',
    'cubes_game.h',
])

objects += map(env.Object, [
    'player_controller.cc',
    'cubes_game.cc',
])

Return('objects')
