Import('manager')

env = manager.CreateEnvironment(depends = ['engine'])

objects = map(env.ObjgenHeader, [
    'player_controller.h',
    'cubes_game.h',
])

objects += map(env.Object, [
    'player_controller.cc',
    'cubes_game.cc',
])

target = env.OrionApplication(name = 'cubes', sources = objects)
Return('target')
