Import('env')

objects = map(env.Object, [
    'material_loader.cc',
    'obj_loader.cc',
    'object_loader.cc',
    'shader_loader.cc',
    'texture_loader.cc',
    'tga_loader.cc',
    'ttf_loader.cc',
])

Return('objects')
