import sys
import util

Import('env')

if sys.platform.startswith('linux'):
    objects = SConscript(dirs = ['linux'])
else:
    util.StopError('Unsupported platform')

objects += map(env.Object, [
    'filesystem.cc',
])

Return('objects')
