Import('env')

objects = map(env.Object, [
    'buffer.cc',
    'commands.cc',
    'fbo.cc',
    'gl.cc',
    'pipeline.cc',
    'program.cc',
    'query_pool.cc',
    'resource.cc',
    'state.cc',
    'texture.cc',
    'vertex_data.cc',
    'window.cc',
])

Return('objects')
