Import('env')

objects = map(env.Object, [
    'material.cc',
    'pass.cc',
    'primitive_renderer.cc',
    'render_manager.cc',
    'render_thread.cc',
    'shader.cc',
    'shader_compiler.cc',
    'shader_parameter.cc',
    'uniform_buffer.cc',
    'utility.cc',
])

Return('objects')
