import os

Import('env', 'engine')

app = env['APP']
objects = SConscript(dirs = [app])
if env['PLATFORM'] == 'win32':
    env.Program(os.path.join('..', app), engine + objects)
else:
    env.Program(os.path.join('..', app), engine + objects, LINK = '$CXX')
