Import('env')

objects = map(env.Object, [
    'buffer.cc',
    'commands.cc',
    'command_buffer.cc',
    'device.cc',
    'loader.cc',
    'manager.cc',
    'memory_manager.cc',
    'pipeline.cc',
    'program.cc',
    'query_pool.cc',
    'queue.cc',
    'render_pass.cc',
    'resource.cc',
    'surface.cc',
    'swapchain.cc',
    'texture.cc',
    'utility.cc',
])

Return('objects')
