sources = map(File, [
    'draw_list.cc',
    'pass.cc',
    'render_manager.cc',
    'scene.cc',
    'scene_entity.cc',
    'scene_light.cc',
    'scene_renderer.cc',
    'scene_view.cc',
    'shader.cc',
    'shader_parameter.cc',
    'uniform_buffer.cc',
    'utility.cc',
])

Return('sources')
