Import('env')

objects = map(env.ObjgenHeader, [
    'include/collision_shape.h',
    'include/physics_material.h',
    'include/physics_system.h',
    'include/rigid_body.h',
])

objects += map(env.Object, [
    'src/collision_shape.cc',
    'src/physics_material.cc',
    'src/physics_system.cc',
    'src/rigid_body.cc',
])

Return('objects')
